[workspace]
members = [
    "mallockit",
    "mallockit/proc_macro",
    "bump",
    "buddy",
    "hoard",
    "sanity",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
debug = true