[package]
name = "hoard"
version = "0.1.0"
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
mallockit = { path = "../mallockit" }
spin = { version="0.9", features = ["std"] }
array-const-fn-init = "0.1.1"