[package]
name = "mallockit"
version = "0.1.0"
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
errno = "0.2"
spin = "0.9"
ctor = "0.1"
mallockit_proc_macro = { path = "./proc_macro" }

[build-dependencies]
yaml-rust = "0.4.5"
shell-words = "1.0.0"

[dev-dependencies]
concat-idents = "1.1.2"

[features]
default = [ "transparent_huge_page" ]
transparent_huge_page = []
slow_assert = []
stat = []
slow_tests = []