[package]
name = "rs-alloc-example"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
hoard = { path = "../hoard" }
toml = "0.8.13"
