[build]
rustflags = ["-Z", "tls_model=initial-exec"]
# rustflags = ["-Z", "tls_model=initial-exec", "-C", "force-frame-pointers=yes"]

[alias]
# Helper command to run a program with a malloc implementation
x = "run -p mallockit-dev-tools --quiet --"
